Exception AttributeError: "'NoneType' object has no attribute 'stdout'" in <bound method Tee.__del__ of <__main__.Tee object at 0x0394EFB0>> ignored
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM5: [Error 121] The semaphore timeout period has expired.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM5: [Error 121] The semaphore timeout period has expired.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM6: [Error 5] Access is denied.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Traceback (most recent call last):
  File "pronterface.py", line 1566, in connect
  File "printcore.pyc", line 76, in connect
  File "serial\serialwin32.pyc", line 30, in __init__
  File "serial\serialutil.pyc", line 260, in __init__
  File "serial\serialwin32.pyc", line 56, in open
serial.serialutil.SerialException: could not open port COM12: [Error 2] The system cannot find the file specified.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyc", line 532, in __bootstrap_inner
  File "threading.pyc", line 484, in run
  File "printcore.pyc", line 97, in _listen
  File "io.pyc", line 520, in readline
  File "serial\serialwin32.pyc", line 212, in read
ValueError: Attempting to use a port that is not open

